project:
  type: website
  output-dir: docs

website:
  title: "MindMeld"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
    right:
      - about.qmd
    

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



